name: jvm-build-deploy
run-name: Build and deploy the app as a traditional JVM application
on:
  push:
    branches:
      - non-aot
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  mvn-build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8-openjdk-18-slim
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Maven Build
        run: mvn -B package
      - name: Copy artifacts to Staging
        run: cd target && mv sticky-note-manager*.jar app.jar && mkdir ../staging && cp app.jar ../staging && cp ../docker/Dockerfile ../staging
      - name: Upload artifact for usage in next job
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
  image-build:
    needs: mvn-build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from previous job
        uses: actions/download-artifact@v3
        with:
          name: staging
      - name: Docker Build
        run: docker build -t ${{ env.IMAGE_NAME }}
      - name: Docker Hub Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Push
        run: docker push ${{ env.IMAGE_NAME }}