name: jvm-build-deploy
run-name: Build and deploy the app as a traditional JVM application
on:
  push:
    branches:
      - non-aot
env:
  REGISTRY: ghcr.io

jobs:
  mvn-build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8-openjdk-18-slim
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Maven Build
        run: mvn -B package
      - name: Copy artifacts to Staging
        run: cd target && mv sticky-note-manager*.jar app.jar && mkdir ../staging && cp app.jar ../staging && cp ../docker/Dockerfile ../staging
      - name: Upload artifact for usage in next job
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
  image-build:
    needs: mvn-build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from previous job
        uses: actions/download-artifact@v3
        with:
          name: Package
      - name: Container Registry Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker Meta Data
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{env.REGISTRY}}/${{ github.repository }}
      - name: Build & Push to Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
#  k8s-deploy:
#    needs: image-build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Azure Login
